# Generated by Django 2.2.1 on 2019-06-01 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20190601_2138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='image_field',
            new_name='image',
        ),
    ]
